CREATE TABLE dbo.Peoplesoft_SO001HRORG_Audit
(
    AuditId          BIGINT IDENTITY(1,1) PRIMARY KEY,
    RunId            UNIQUEIDENTIFIER NOT NULL,
    AuditDtmUtc      DATETIME2(0)     NOT NULL
        CONSTRAINT DF_Peoplesoft_SO001HRORG_Audit_AuditDtmUtc DEFAULT SYSUTCDATETIME(),

    ActionType       VARCHAR(12)      NOT NULL,  -- INSERT / UPDATE / SOFT_DELETE / REACTIVATE
    PosPosition      NVARCHAR(20)     NOT NULL,

    OldRowHash       VARBINARY(32)    NULL,
    NewRowHash       VARBINARY(32)    NULL,

    OldIsActive      BIT              NULL,
    NewIsActive      BIT              NULL,

    -- OLD values
    OldOrganization        NVARCHAR(255) NULL,
    OldLevel1              NVARCHAR(255) NULL,
    OldLevel2              NVARCHAR(255) NULL,
    OldLevel3              NVARCHAR(255) NULL,
    OldPosBusinessUnit     NVARCHAR(255) NULL,
    OldPosBU               NVARCHAR(20)  NULL,
    OldPosDepartment       NVARCHAR(255) NULL,
    OldPosDeptId           NVARCHAR(50)  NULL,
    OldTitle               NVARCHAR(255) NULL,
    OldPosRole             NVARCHAR(255) NULL,
    OldPosJobCode          NVARCHAR(50)  NULL,
    OldPosClassification   NVARCHAR(255) NULL,
    OldSupervisorPos       NVARCHAR(20)  NULL,
    OldSupervisorName      NVARCHAR(255) NULL,
    OldDirect              INT           NULL,
    OldIndirect            INT           NULL,
    OldCity                NVARCHAR(255) NULL,
    OldStatus              NVARCHAR(50)  NULL,
    OldRT                  NVARCHAR(10)  NULL,
    OldFP                  NVARCHAR(10)  NULL,
    OldBudgetted           NVARCHAR(10)  NULL,
    OldEmpty               NVARCHAR(10)  NULL,
    OldVacant              NVARCHAR(10)  NULL,
    OldTrueVacancy         NVARCHAR(10)  NULL,
    OldFuture              NVARCHAR(10)  NULL,
    OldLastFilled          NVARCHAR(50)  NULL,
    OldLastFilledB         NVARCHAR(50)  NULL,
    OldLastFilledBase      NVARCHAR(50)  NULL,
    OldEmplBU              NVARCHAR(20)  NULL,
    OldEmplDeptId          NVARCHAR(50)  NULL,
    OldJobRole             NVARCHAR(255) NULL,
    OldEmplJobCode         NVARCHAR(50)  NULL,
    OldEmplClassification  NVARCHAR(255) NULL,
    OldGrade               NVARCHAR(10)  NULL,
    OldStep                NVARCHAR(50)  NULL,
    OldSalaryType          NVARCHAR(50)  NULL,
    OldType                NVARCHAR(50)  NULL,
    OldStandardHours       NVARCHAR(20)  NULL,
    OldBase                NVARCHAR(10)  NULL,
    OldName                NVARCHAR(255) NULL,
    OldEmplId              NVARCHAR(20)  NULL,
    OldEmplStatus          NVARCHAR(50)  NULL,
    OldAppt                NVARCHAR(50)  NULL,
    OldAge                 INT           NULL,
    OldPosClassMax         NVARCHAR(50)  NULL,
    OldJobClassMax         NVARCHAR(50)  NULL,
    OldAnnual              NVARCHAR(50)  NULL,
    OldAbbr                NVARCHAR(50)  NULL,
    OldAdminPlan           NVARCHAR(50)  NULL,
    OldAMA                 NVARCHAR(50)  NULL,
    OldAMALimit            NVARCHAR(50)  NULL,
    OldCAD                 NVARCHAR(50)  NULL,
    OldCADLimit            NVARCHAR(50)  NULL,
    OldSPP                 NVARCHAR(50)  NULL,
    OldSPPLimit            NVARCHAR(50)  NULL,
    OldTAJ                 NVARCHAR(50)  NULL,
    OldTAJLimit            NVARCHAR(50)  NULL,
    OldFutureTermDate      NVARCHAR(50)  NULL,
    OldFutureTermReason    NVARCHAR(255) NULL,
    OldTAStatus            NVARCHAR(50)  NULL,
    OldTAStartDate         NVARCHAR(50)  NULL,
    OldTAReturnDate        NVARCHAR(50)  NULL,
    OldTAReturnTo          NVARCHAR(50)  NULL,
    OldTAReturnBU          NVARCHAR(20)  NULL,
    OldTAReturnDeptId      NVARCHAR(50)  NULL,
    OldTAReturnJobCode     NVARCHAR(50)  NULL,
    OldTAReturnGrade       NVARCHAR(10)  NULL,
    OldTAReturnPosition    NVARCHAR(20)  NULL,
    OldTAReturnSupervisor  NVARCHAR(255) NULL,
    OldTAReturnAbbr        NVARCHAR(50)  NULL,
    OldLeaveReason         NVARCHAR(255) NULL,
    OldLeaveStart          NVARCHAR(50)  NULL,
    OldLeaveReturn         NVARCHAR(50)  NULL,
    OldQ                   NVARCHAR(50)  NULL,
    OldMaildropCity        NVARCHAR(255) NULL,

    -- NEW values
    NewOrganization        NVARCHAR(255) NULL,
    NewLevel1              NVARCHAR(255) NULL,
    NewLevel2              NVARCHAR(255) NULL,
    NewLevel3              NVARCHAR(255) NULL,
    NewPosBusinessUnit     NVARCHAR(255) NULL,
    NewPosBU               NVARCHAR(20)  NULL,
    NewPosDepartment       NVARCHAR(255) NULL,
    NewPosDeptId           NVARCHAR(50)  NULL,
    NewTitle               NVARCHAR(255) NULL,
    NewPosRole             NVARCHAR(255) NULL,
    NewPosJobCode          NVARCHAR(50)  NULL,
    NewPosClassification   NVARCHAR(255) NULL,
    NewSupervisorPos       NVARCHAR(20)  NULL,
    NewSupervisorName      NVARCHAR(255) NULL,
    NewDirect              INT           NULL,
    NewIndirect            INT           NULL,
    NewCity                NVARCHAR(255) NULL,
    NewStatus              NVARCHAR(50)  NULL,
    NewRT                  NVARCHAR(10)  NULL,
    NewFP                  NVARCHAR(10)  NULL,
    NewBudgetted           NVARCHAR(10)  NULL,
    NewEmpty               NVARCHAR(10)  NULL,
    NewVacant              NVARCHAR(10)  NULL,
    NewTrueVacancy         NVARCHAR(10)  NULL,
    NewFuture              NVARCHAR(10)  NULL,
    NewLastFilled          NVARCHAR(50)  NULL,
    NewLastFilledB         NVARCHAR(50)  NULL,
    NewLastFilledBase      NVARCHAR(50)  NULL,
    NewEmplBU              NVARCHAR(20)  NULL,
    NewEmplDeptId          NVARCHAR(50)  NULL,
    NewJobRole             NVARCHAR(255) NULL,
    NewEmplJobCode         NVARCHAR(50)  NULL,
    NewEmplClassification  NVARCHAR(255) NULL,
    NewGrade               NVARCHAR(10)  NULL,
    NewStep                NVARCHAR(50)  NULL,
    NewSalaryType          NVARCHAR(50)  NULL,
    NewType                NVARCHAR(50)  NULL,
    NewStandardHours       NVARCHAR(20)  NULL,
    NewBase                NVARCHAR(10)  NULL,
    NewName                NVARCHAR(255) NULL,
    NewEmplId              NVARCHAR(20)  NULL,
    NewEmplStatus          NVARCHAR(50)  NULL,
    NewAppt                NVARCHAR(50)  NULL,
    NewAge                 INT           NULL,
    NewPosClassMax         NVARCHAR(50)  NULL,
    NewJobClassMax         NVARCHAR(50)  NULL,
    NewAnnual              NVARCHAR(50)  NULL,
    NewAbbr                NVARCHAR(50)  NULL,
    NewAdminPlan           NVARCHAR(50)  NULL,
    NewAMA                 NVARCHAR(50)  NULL,
    NewAMALimit            NVARCHAR(50)  NULL,
    NewCAD                 NVARCHAR(50)  NULL,
    NewCADLimit            NVARCHAR(50)  NULL,
    NewSPP                 NVARCHAR(50)  NULL,
    NewSPPLimit            NVARCHAR(50)  NULL,
    NewTAJ                 NVARCHAR(50)  NULL,
    NewTAJLimit            NVARCHAR(50)  NULL,
    NewFutureTermDate      NVARCHAR(50)  NULL,
    NewFutureTermReason    NVARCHAR(255) NULL,
    NewTAStatus            NVARCHAR(50)  NULL,
    NewTAStartDate         NVARCHAR(50)  NULL,
    NewTAReturnDate        NVARCHAR(50)  NULL,
    NewTAReturnTo          NVARCHAR(50)  NULL,
    NewTAReturnBU          NVARCHAR(20)  NULL,
    NewTAReturnDeptId      NVARCHAR(50)  NULL,
    NewTAReturnJobCode     NVARCHAR(50)  NULL,
    NewTAReturnGrade       NVARCHAR(10)  NULL,
    NewTAReturnPosition    NVARCHAR(20)  NULL,
    NewTAReturnSupervisor  NVARCHAR(255) NULL,
    NewTAReturnAbbr        NVARCHAR(50)  NULL,
    NewLeaveReason         NVARCHAR(255) NULL,
    NewLeaveStart          NVARCHAR(50)  NULL,
    NewLeaveReturn         NVARCHAR(50)  NULL,
    NewQ                   NVARCHAR(50)  NULL,
    NewMaildropCity        NVARCHAR(255) NULL
);
GO

CREATE INDEX IX_Peoplesoft_SO001HRORG_Audit_RunId
ON dbo.Peoplesoft_SO001HRORG_Audit (RunId, ActionType);
GO
