IF OBJECT_ID('dbo.Peoplesoft_SHR010HRORG_Audit', 'U') IS NOT NULL
    DROP TABLE dbo.Peoplesoft_SHR010HRORG_Audit;
GO

CREATE TABLE dbo.Peoplesoft_SHR010HRORG_Audit
(
    AuditId          BIGINT IDENTITY(1,1) PRIMARY KEY,
    RunId            UNIQUEIDENTIFIER NOT NULL,
    AuditDtmUtc      DATETIME2(0)     NOT NULL
        CONSTRAINT DF_Peoplesoft_SHR010HRORG_Audit_AuditDtmUtc DEFAULT SYSUTCDATETIME(),

    ActionType       VARCHAR(12)      NOT NULL,  -- INSERT / UPDATE / SOFT_DELETE / REACTIVATE
    EmplId           NVARCHAR(20)     NOT NULL,  -- Business key

    OldRowHash       VARBINARY(32)    NULL,
    NewRowHash       VARBINARY(32)    NULL,

    OldIsActive      BIT              NULL,
    NewIsActive      BIT              NULL,

    -- NOTE: AsOfDate is excluded from audit (report metadata — same for all rows per run).

    -- OLD values
    OldName                         NVARCHAR(255)  NULL,
    OldIdir                         NVARCHAR(50)   NULL,
    OldEmailId                      NVARCHAR(255)  NULL,
    OldEmplStatus                   NVARCHAR(50)   NULL,
    OldEmplType                     NVARCHAR(10)   NULL,
    OldEmplCtg                      NVARCHAR(50)   NULL,
    OldEmplCtgL1                    NVARCHAR(50)   NULL,
    OldEmplRcd                      INT            NULL,
    OldApptStatus                   NVARCHAR(50)   NULL,
    OldApptStatusCode               NVARCHAR(10)   NULL,
    OldBirthdate                    DATE           NULL,
    OldHireDt                       DATE           NULL,
    OldLastHireDt                   DATE           NULL,
    OldMostHistoricDate             DATE           NULL,
    OldFirstDateInOrganization      DATE           NULL,
    OldFirstDateInPosition          DATE           NULL,
    OldFutureReturnDate             DATE           NULL,
    OldPositionNbr                  NVARCHAR(20)   NULL,
    OldTgbBasePosition              NVARCHAR(20)   NULL,
    OldPositionDataDescr            NVARCHAR(255)  NULL,
    OldJobCode                      NVARCHAR(20)   NULL,
    OldJobCodeDescr                 NVARCHAR(255)  NULL,
    OldJobFunction                  NVARCHAR(20)   NULL,
    OldSalAdminPlan                 NVARCHAR(20)   NULL,
    OldGrade                        NVARCHAR(20)   NULL,
    OldStep                         INT            NULL,
    OldStdHours                     DECIMAL(6,2)   NULL,
    OldAnnualRt                     DECIMAL(18,4)  NULL,
    OldCompRate                     DECIMAL(18,4)  NULL,
    OldHourlyRt                     DECIMAL(12,4)  NULL,
    OldOrganization                 NVARCHAR(255)  NULL,
    OldBusinessUnit                 NVARCHAR(20)   NULL,
    OldDeptId                       NVARCHAR(50)   NULL,
    OldDeptDescr                    NVARCHAR(255)  NULL,
    OldLevel1                       NVARCHAR(255)  NULL,
    OldLevel2                       NVARCHAR(255)  NULL,
    OldLevel3                       NVARCHAR(255)  NULL,
    OldDescr                        NVARCHAR(255)  NULL,
    OldCore                         NVARCHAR(20)   NULL,
    OldCoreGovernment               NVARCHAR(50)   NULL,
    OldSector                       NVARCHAR(50)   NULL,
    OldPublicService                NVARCHAR(50)   NULL,
    OldPublicServiceAct             NVARCHAR(50)   NULL,
    OldTreasuryBoard                NVARCHAR(50)   NULL,
    OldOfficerCode                  NVARCHAR(50)   NULL,
    OldNocCode                      NVARCHAR(20)   NULL,
    OldNocCodeDescr                 NVARCHAR(255)  NULL,
    OldReportsTo                    NVARCHAR(20)   NULL,
    OldLocation                     NVARCHAR(50)   NULL,
    OldLocationCity                 NVARCHAR(100)  NULL,
    OldAgeGroup1                    NVARCHAR(10)   NULL,
    OldAgeGroup2                    NVARCHAR(20)   NULL,
    OldAge                          DECIMAL(8,4)   NULL,
    OldGeneration                   NVARCHAR(30)   NULL,
    OldEligibleForPension           NVARCHAR(10)   NULL,
    OldEligibleForUnreducedPension  NVARCHAR(10)   NULL,
    OldSupervisor                   NVARCHAR(255)  NULL,
    OldSupervEmail                  NVARCHAR(255)  NULL,
    OldSupervSalPlan                NVARCHAR(20)   NULL,
    OldSupervisorStatus             NVARCHAR(50)   NULL,
    OldLayoffLeaveStopPayReason     NVARCHAR(255)  NULL,
    OldLayoffLeaveStopPayStartDate  DATE           NULL,

    -- NEW values
    NewName                         NVARCHAR(255)  NULL,
    NewIdir                         NVARCHAR(50)   NULL,
    NewEmailId                      NVARCHAR(255)  NULL,
    NewEmplStatus                   NVARCHAR(50)   NULL,
    NewEmplType                     NVARCHAR(10)   NULL,
    NewEmplCtg                      NVARCHAR(50)   NULL,
    NewEmplCtgL1                    NVARCHAR(50)   NULL,
    NewEmplRcd                      INT            NULL,
    NewApptStatus                   NVARCHAR(50)   NULL,
    NewApptStatusCode               NVARCHAR(10)   NULL,
    NewBirthdate                    DATE           NULL,
    NewHireDt                       DATE           NULL,
    NewLastHireDt                   DATE           NULL,
    NewMostHistoricDate             DATE           NULL,
    NewFirstDateInOrganization      DATE           NULL,
    NewFirstDateInPosition          DATE           NULL,
    NewFutureReturnDate             DATE           NULL,
    NewPositionNbr                  NVARCHAR(20)   NULL,
    NewTgbBasePosition              NVARCHAR(20)   NULL,
    NewPositionDataDescr            NVARCHAR(255)  NULL,
    NewJobCode                      NVARCHAR(20)   NULL,
    NewJobCodeDescr                 NVARCHAR(255)  NULL,
    NewJobFunction                  NVARCHAR(20)   NULL,
    NewSalAdminPlan                 NVARCHAR(20)   NULL,
    NewGrade                        NVARCHAR(20)   NULL,
    NewStep                         INT            NULL,
    NewStdHours                     DECIMAL(6,2)   NULL,
    NewAnnualRt                     DECIMAL(18,4)  NULL,
    NewCompRate                     DECIMAL(18,4)  NULL,
    NewHourlyRt                     DECIMAL(12,4)  NULL,
    NewOrganization                 NVARCHAR(255)  NULL,
    NewBusinessUnit                 NVARCHAR(20)   NULL,
    NewDeptId                       NVARCHAR(50)   NULL,
    NewDeptDescr                    NVARCHAR(255)  NULL,
    NewLevel1                       NVARCHAR(255)  NULL,
    NewLevel2                       NVARCHAR(255)  NULL,
    NewLevel3                       NVARCHAR(255)  NULL,
    NewDescr                        NVARCHAR(255)  NULL,
    NewCore                         NVARCHAR(20)   NULL,
    NewCoreGovernment               NVARCHAR(50)   NULL,
    NewSector                       NVARCHAR(50)   NULL,
    NewPublicService                NVARCHAR(50)   NULL,
    NewPublicServiceAct             NVARCHAR(50)   NULL,
    NewTreasuryBoard                NVARCHAR(50)   NULL,
    NewOfficerCode                  NVARCHAR(50)   NULL,
    NewNocCode                      NVARCHAR(20)   NULL,
    NewNocCodeDescr                 NVARCHAR(255)  NULL,
    NewReportsTo                    NVARCHAR(20)   NULL,
    NewLocation                     NVARCHAR(50)   NULL,
    NewLocationCity                 NVARCHAR(100)  NULL,
    NewAgeGroup1                    NVARCHAR(10)   NULL,
    NewAgeGroup2                    NVARCHAR(20)   NULL,
    NewAge                          DECIMAL(8,4)   NULL,
    NewGeneration                   NVARCHAR(30)   NULL,
    NewEligibleForPension           NVARCHAR(10)   NULL,
    NewEligibleForUnreducedPension  NVARCHAR(10)   NULL,
    NewSupervisor                   NVARCHAR(255)  NULL,
    NewSupervEmail                  NVARCHAR(255)  NULL,
    NewSupervSalPlan                NVARCHAR(20)   NULL,
    NewSupervisorStatus             NVARCHAR(50)   NULL,
    NewLayoffLeaveStopPayReason     NVARCHAR(255)  NULL,
    NewLayoffLeaveStopPayStartDate  DATE           NULL
);
GO

CREATE INDEX IX_Peoplesoft_SHR010HRORG_Audit_RunId
    ON dbo.Peoplesoft_SHR010HRORG_Audit (RunId);
GO

CREATE INDEX IX_Peoplesoft_SHR010HRORG_Audit_EmplId
    ON dbo.Peoplesoft_SHR010HRORG_Audit (EmplId);
GO
